### ISSUE TITLE
Pipe issue

### ISSUE THREAD

**Issue by JeongSu0880** [haddol7/minishell#20]
1. cat I cat 을 했을 때 ps→ Isof I grep ^cat 를 보면 (Is) 하고 좀비 프로세스로 뜸.
2. pwd I (cat && Is) I cat 일때 처리 순서가 bash와 다름
3. ls l cat && ls l cat 와 같이 2번과 같은 경우에서 subshell 이 없는 경우에도 동작이 다름 -> 파이프 에러인 것 같다. 
4. 비슷한 경우로 sleep 10 l sleep 5 l sleep 3 인 경우에도 경국에는 잘 닫히지민 중간에는 좀비 프로세스 상태로 남아있음.

**Comment by haddol7** [comment]
ls | (cat) | cat

**Comment by haddol7** [comment]
1번 문제는 fd leaks로 인한 문제. pipe 처리하는 함수에서 부모 프로세스에 있는 pipe fd를 제대로 close() 해줘서 해결

**Comment by haddol7** [comment]
4번 문제 또한 해결 완료
